datadev:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/dev:/data

datatest:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/tests:/data

db:
  image: postgres:9.5
  volumes:
    - ./data/dev/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=webapp
    - POSTGRES_PASSWORD=webapp

cache:
  image: memcached:1.4

runserver:
  build: .
  command: runserver
  environment:
    - DBUSER=webbapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
  ports:
    - "8000:8000"
  volumes_from:
    - datadev
  links:
    - db
    - cache

uwsgi:
  image: bpadatatracker_runserver
  command: uwsgi
  environment:
    - DBUSER=webapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
    - WAIT_FOR_RUNSERVER=1
  ports:
    - "9000:9000"
    - "9001:9001"
    - "9100:9100"
    - "9101:9101"
  volumes_from:
    - datadev
  links:
    - db
    - cache
    - runserver:web

nginx:
  image: muccg/nginx-uwsgi:1.9
  links:
    - uwsgi
  ports:
    - "8443:443"
  volumes_from:
    - datadev
  volumes:
    - ./data/nginx:/data
