# -*- coding: utf-8 -*-
FROM postgres:9.4 
MAINTAINER https://github.com/muccg/bpa-track/

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  binutils \
  libproj-dev \
  gdal-bin \
  postgis* \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN env --unset=DEBIAN_FRONTEND

