data:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/dev:/data

db:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=webapp
    - POSTGRES_PASSWORD=webapp
  ports:
    - 5432

cache:
  image: memcached:1.4


web:
  build: .
  command: runserver
  environment:
    - DJANGO_SETTINGS_MODULE=bpatrack.settings
    - DBUSER=webapp
  volumes_from:
    - data
  ports:
    - "8000:8000"
  links:
    - db
    - cache

