datadev:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/dev:/data

db:
  build: .
  dockerfile: Dockerfile-postgis
  environment:
    - POSTGRES_USER=bpatrack
    - POSTGRES_PASSWORD=bpatrack
  ports:
    - "5432"

cache:
  image: memcached:1.4

runserver:
  build: .
  dockerfile: Dockerfile-dev
  command: runserver
  environment:
    - DJANGO_SETTINGS_MODULE=bpatrack.config.settings.local
    - DBUSER=bpatrack
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
    - DJANGO_MAILGUN_API_KEY=${DJANGO_MAILGUN_API_KEY}
  ports:
    - "8000:8000"
  volumes_from:
    - datadev
  links:
    - db
    - cache

uwsgi:
  image: bpatrack_runserver
  command: uwsgi
  environment:
    - DBUSER=bpatrack
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
    - WAIT_FOR_RUNSERVER=1
  ports:
    - "9000:9000"
    - "9001:9001"
    - "9100:9100"
    - "9101:9101"
  volumes_from:
    - datadev
  links:
    - db
    - cache
    - runserver

nginx:
  image: muccg/nginx-uwsgi:1.9
  ports:
    - "8443:443"
  links:
    - uwsgi
