datadev:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/dev:/data

datatest:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/tests:/data

db:
  image: postgres:9.5
  volumes:
    - ./data/dev/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=webapp
    - POSTGRES_PASSWORD=webapp

cache:
  image: memcached:1.4

django:
  build: .
  user: django
  links:
    - db 
  command: /gunicorn.sh
  env_file: dev.env

nginx:
  build: ./compose/nginx
  links:
    - django
  ports:
    - "0.0.0.0:80:80"

