# -*- coding: utf-8 -*-
FROM muccg/bpatrack-base
MAINTAINER https://github.com/muccg/bpa-track/

ARG ARG_GIT_TAG=next_release

ENV GIT_TAG $ARG_GIT_TAG
ARG PIP_OPTS="--no-cache-dir"
ENV PIP_INDEX_URL="https://pypi.python.org/simple"
ENV PIP_TRUSTED_HOST="127.0.0.1"

# Project specific deps
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  libjpeg-dev \
  libpq-dev \
  libxml2-dev \
  libxslt1-dev \
  libssl-dev \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN env --unset=DEBIAN_FRONTEND

WORKDIR /app
COPY .version /.version
RUN cat /.version

# ADD https://raw.githubusercontent.com/muccg/bpa-track/${GIT_TAG}/docker-entrypoint.sh /app/docker-entrypoint.sh
COPY docker-entrypoint.sh /app/
RUN chmod +x /app/docker-entrypoint.sh

VOLUME ["/data"]

ENV HOME /data
WORKDIR /data

# entrypoint shell script that by default starts runserver
ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["tarball"]
