# -*- coding: utf-8 -*-
FROM muccg/python-base:debian8-3.5
MAINTAINER https://github.com/muccg/bpa-track/

ARG ARG_GIT_TAG
ENV GIT_TAG $ARG_GIT_TAG

ENV VIRTUAL_ENV /env
ENV PATH $VIRTUAL_ENV/bin:$PATH
ENV DEPLOYMENT prod
ENV PRODUCTION 1
ENV DEBUG 0
ENV STATIC_ROOT /data/static
ENV WRITABLE_DIRECTORY /data/scratch
ENV MEDIA_ROOT /data/static/media
ENV LOG_DIRECTORY /data/log
ENV DJANGO_SETTINGS_MODULE bpatrack.config.settings.production

# Project specific deps
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  libpq5 \
  libxml2 \
  libxslt1.1 \
  imagemagick \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN env --unset=DEBIAN_FRONTEND

ENTRYPOINT ["/bin/sh"]
