# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('AGRF', 'Australian Genome Research Facility (AGRF)'), ('RAM', 'Ramaciotti Centre for Genomics')], max_length=3)),
                ('extraction_id', models.CharField(max_length=12)),
                ('batch_number', models.CharField(max_length=20)),
                ('date_received', models.DateField()),
            ],
        ),
    ]
