# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 04:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amplicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Extraction ID')),
                ('target', models.CharField(choices=[('16S', '16S'), ('ITS', 'ITS'), ('18S', '18S'), ('A16S', 'A16S')], max_length=4, verbose_name='Type')),
                ('metadata_filename', models.CharField(max_length=100, verbose_name='Metadata Filename')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_amplicon_facility', to='common.Facility', verbose_name='Sequencing Facility')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Amplicon Sequences',
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Dataset')),
                ('transfer_to_archive_date', models.DateField(verbose_name='Transfer to Archive Date')),
                ('ticket_url', models.URLField(verbose_name='JIRA')),
                ('downloads_url', models.URLField(verbose_name='Downloads')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_dataset_facility', to='common.Facility', verbose_name='Sequencing Facility')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='Metagenomic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Extraction ID')),
                ('metadata_filename', models.CharField(max_length=100, verbose_name='Metadata Filename')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_metagenomic_facility', to='common.Facility', verbose_name='Sequencing Facility')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Metagenomic Sequences',
            },
        ),
        migrations.CreateModel(
            name='SampleReceived',
            fields=[
                ('extraction_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=20)),
                ('date_received', models.DateField()),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Facility', verbose_name='Sequencing Facility')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample Received',
                'verbose_name_plural': 'Samples Received',
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_to_facility_date', models.DateField(verbose_name='Transfer to Facility Date')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('data_type', models.CharField(max_length=50, verbose_name='Data Type')),
                ('folder_name', models.CharField(max_length=100, verbose_name='Folder')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.DataSet')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Facility')),
            ],
            options={
                'verbose_name': 'Transfer Log',
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
