# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20160113_1433'),
        ('base', '0010_auto_20160202_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metagenomic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Extraction ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Facility', verbose_name='Sequencing Facility')),
            ],
            options={
                'verbose_name_plural': 'Metagenomic Sequences',
            },
        ),
    ]
