# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20160113_1433'),
        ('base', '0013_auto_20160202_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_to_facility_date', models.DateField(verbose_name='Transfer to Facility Date')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('data_type', models.CharField(max_length=50, verbose_name='Data Type')),
                ('folder_name', models.CharField(max_length=100, verbose_name='Folder')),
                ('transfer_to_archive_date', models.DateField(verbose_name='Transfer to Archive Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('ticket_url', models.URLField(verbose_name='Dataset')),
                ('downloads_url', models.URLField(verbose_name='Downloads')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Facility', verbose_name='Sequencing Facility')),
            ],
            options={
                'verbose_name': 'Transfer Log',
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
