# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_dataset_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferlog',
            name='downloads_url',
        ),
        migrations.RemoveField(
            model_name='transferlog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='transferlog',
            name='ticket_url',
        ),
        migrations.RemoveField(
            model_name='transferlog',
            name='transfer_to_archive_date',
        ),
        migrations.AddField(
            model_name='transferlog',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.DataSet'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Dataset'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Facility'),
        ),
    ]
