# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplereception',
            name='vendor',
            field=models.CharField(choices=[('AGRF', 'Australian Genome Research Facility (AGRF)'), ('RAM', 'Ramaciotti Centre for Genomics')], max_length=5),
        ),
    ]
