# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20160110_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplereceived',
            options={'verbose_name': 'Sample Received', 'verbose_name_plural': 'Samples Received'},
        ),
        migrations.AddField(
            model_name='samplereceived',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
