# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20160113_1433'),
        ('base', '0009_auto_20160113_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amplicon',
            old_name='sample_extraction_id',
            new_name='extraction_id',
        ),
        migrations.RemoveField(
            model_name='amplicon',
            name='sequencing_facility',
        ),
        migrations.AddField(
            model_name='amplicon',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Facility', verbose_name='Sequencing Facility'),
        ),
    ]
