# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_metagenomic'),
    ]

    operations = [
        migrations.AddField(
            model_name='amplicon',
            name='metadata_filename',
            field=models.TextField(default='horseshit', verbose_name='Metadata Filename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metagenomic',
            name='metadata_filename',
            field=models.TextField(default='horse', verbose_name='Metadata Filename'),
            preserve_default=False,
        ),
    ]
