# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 03:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20160113_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Position')),
                ('dept', models.IntegerField(verbose_name='Depth')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('location_description', models.TextField(verbose_name='Location Description')),
            ],
        ),
    ]
