# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 04:04
from __future__ import unicode_literals

import autoslug.fields
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=255, populate_from='location_description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Represented as (longitude, latitude)', srid=4326, verbose_name='Position'),
        ),
    ]
