# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 04:10
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20160323_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='point', unique=True),
        ),
    ]
