# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20160323_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='dept',
            new_name='depth',
        ),
    ]
