# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 02:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20160323_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='site',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Represented as (longitude, latitude)', primary_key=True, serialize=False, srid=4326, verbose_name='Position'),
        ),
    ]
