# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 06:37
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20160324_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='location_description', unique=True),
        ),
    ]
