# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20160330_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='depth',
        ),
    ]
