# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_site_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='slug',
        ),
    ]
