# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20160112_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Facility Name'),
        ),
    ]
