# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160108_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplereception',
            name='id',
        ),
        migrations.AlterField(
            model_name='samplereception',
            name='extraction_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samplereception',
            name='vendor',
            field=models.CharField(choices=[('AGRF', 'Australian Genome Research Facility (AGRF)'), ('RAM', 'Ramaciotti Centre for Genomics')], max_length=5, null=True),
        ),
    ]
