# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('base', '0005_auto_20160110_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amplicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpa_id', models.IntegerField(verbose_name='BPA ID')),
                ('sample_extraction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sample Extraction ID')),
                ('target', models.CharField(choices=[('16S', '16S'), ('ITS', 'ITS'), ('18S', '18S'), ('A16S', 'A16S')], max_length=4, verbose_name='Type')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('sequencing_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_amplicon', to='common.Facility', verbose_name='Sequencing Facility')),
            ],
            options={
                'verbose_name_plural': 'Amplicon Sequences',
            },
        ),
        migrations.RemoveField(
            model_name='samplereceived',
            name='vendor',
        ),
        migrations.AddField(
            model_name='samplereceived',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Facility', verbose_name='Sequencing Facility'),
        ),
    ]
