# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160112_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amplicon',
            name='bpa_id',
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='sample_extraction_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sample Extraction ID'),
        ),
    ]
