# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160113_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amplicon',
            name='sample_extraction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Extraction ID'),
        ),
    ]
