# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_auto_20160113_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amplicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Extraction ID')),
                ('target', models.CharField(choices=[('16S', '16S'), ('ITS', 'ITS'), ('18S', '18S'), ('A16S', 'A16S')], max_length=4, verbose_name='Type')),
                ('metadata_filename', models.CharField(max_length=100, verbose_name='Metadata Filename')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marine_amplicon_facility', to='common.Facility', verbose_name='Sequencing Facility')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Amplicon Sequences',
            },
        ),
        migrations.CreateModel(
            name='Metagenomic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Extraction ID')),
                ('metadata_filename', models.CharField(max_length=100, verbose_name='Metadata Filename')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marine_metagenomic_facility', to='common.Facility', verbose_name='Sequencing Facility')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Metagenomic Sequences',
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_to_facility_date', models.DateField(verbose_name='Transfer to Facility Date')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('data_type', models.CharField(max_length=50, verbose_name='Data Type')),
                ('folder_name', models.CharField(max_length=100, verbose_name='Folder')),
                ('transfer_to_archive_date', models.DateField(verbose_name='Transfer to Archive Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('ticket_url', models.URLField(verbose_name='Dataset')),
                ('downloads_url', models.URLField(verbose_name='Downloads')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marine_transferlog_facility', to='common.Facility', verbose_name='Sequencing Facility')),
            ],
            options={
                'verbose_name': 'Transfer Log',
                'abstract': False,
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
