# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextualpelagic',
            options={'verbose_name': 'Pelagic Contextual Data', 'verbose_name_plural': 'Pelagic Contextual Data'},
        ),
    ]
