# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleStateTrack',
            fields=[
                ('extraction_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Sample Extraction ID')),
                ('quality_check_preformed', models.BooleanField(default=False, verbose_name='Quality Checked')),
                ('metagenomics_data_generated', models.BooleanField(default=False, verbose_name='Metagenomics Data Generated')),
                ('amplicon_16s_data_generated', models.BooleanField(default=False, verbose_name='Amplicon 16S Data Generated')),
                ('amplicon_18s_data_generated', models.BooleanField(default=False, verbose_name='Amplicon 18S Data Generated')),
                ('amplicon_ITS_data_generated', models.BooleanField(default=False, verbose_name='Amplicon ITS Data Generated')),
                ('minimum_contextual_data_received', models.BooleanField(default=False, verbose_name='Minimum Contextual Data Received')),
                ('full_contextual_data_received', models.BooleanField(default=False, verbose_name='Full Contextual Data Received')),
            ],
            options={
                'verbose_name': 'Sample State Track Log',
            },
        ),
    ]
