# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0002_auto_20160413_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextualopenwater',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='contextualpelagic',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='coral',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='seagrass',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='seaweed',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='sediment',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='sponge',
            name='dept',
        ),
        migrations.AddField(
            model_name='contextualopenwater',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depth (m)'),
        ),
        migrations.AddField(
            model_name='contextualpelagic',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depth (m)'),
        ),
        migrations.AddField(
            model_name='coral',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depth (m)'),
        ),
        migrations.AddField(
            model_name='seagrass',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depth (m)'),
        ),
        migrations.AddField(
            model_name='seaweed',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depth (m)'),
        ),
        migrations.AddField(
            model_name='sediment',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depth (m)'),
        ),
        migrations.AddField(
            model_name='sponge',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depth (m)'),
        ),
        migrations.AlterField(
            model_name='contextualopenwater',
            name='date_sampled',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sampled'),
        ),
        migrations.AlterField(
            model_name='contextualopenwater',
            name='time_sampled',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Sampled'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='date_sampled',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sampled'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='time_sampled',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Sampled'),
        ),
        migrations.AlterField(
            model_name='coral',
            name='date_sampled',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sampled'),
        ),
        migrations.AlterField(
            model_name='coral',
            name='time_sampled',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Sampled'),
        ),
        migrations.AlterField(
            model_name='seagrass',
            name='date_sampled',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sampled'),
        ),
        migrations.AlterField(
            model_name='seagrass',
            name='time_sampled',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Sampled'),
        ),
        migrations.AlterField(
            model_name='seaweed',
            name='date_sampled',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sampled'),
        ),
        migrations.AlterField(
            model_name='seaweed',
            name='time_sampled',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Sampled'),
        ),
        migrations.AlterField(
            model_name='sediment',
            name='date_sampled',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sampled'),
        ),
        migrations.AlterField(
            model_name='sediment',
            name='time_sampled',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Sampled'),
        ),
        migrations.AlterField(
            model_name='sponge',
            name='date_sampled',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sampled'),
        ),
        migrations.AlterField(
            model_name='sponge',
            name='time_sampled',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Sampled'),
        ),
    ]
