# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0005_auto_20160314_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextualpelagic',
            name='alkalinity_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total alkalinity (μmol/kg)'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='ammonium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ammonium (μmol/L)'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='carbon_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='% total carbon'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='chlorophyl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chlorophyll a (μg/L)'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='co2_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total CO2 (μmol/kg)'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='conductivity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Conductivity [S/m]'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='flux',
            field=models.IntegerField(blank=True, null=True, verbose_name='Light intensity (lux)'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='host_species',
            field=models.TextField(blank=True, null=True, verbose_name='Host Species'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='inorganic_carbon_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='% total inorganc carbon'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='location_description',
            field=models.TextField(verbose_name='Location Description'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='microbial_abandance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Microbial abundance (cells per ml)'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='nitrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nitrate/Nitrite (μmol/L)'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='oxygen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oxygen (μmol/L) Lab'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='oxygen_ctd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oxygen (ml/L) CDT'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='ph',
            field=models.IntegerField(blank=True, null=True, verbose_name='pH Level H20'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='phosphate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phosphate (μmol/L)'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='salinity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salinity [PSU] Laboratory'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature [ITS-90, deg C]'),
        ),
        migrations.AlterField(
            model_name='contextualpelagic',
            name='turbitity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Turbidity (Upoly 0, WET Labs FLNTURT)'),
        ),
    ]
