# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0008_coral_seagrass_seaweed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sediment',
            fields=[
                ('bpa_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='BPA ID')),
                ('date_sampled', models.DateField(verbose_name='Date Sampled')),
                ('time_sampled', models.TimeField(verbose_name='Time Sampled')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('dept', models.IntegerField(verbose_name='Depth')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('location_description', models.TextField(verbose_name='Location Description')),
                ('host_species', models.TextField(blank=True, null=True, verbose_name='Host Species')),
                ('carbon', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% total carbon')),
                ('sediment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% fine sediment')),
                ('nitrogen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% total nitrogen')),
                ('phosphorous', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% total phosphorous')),
                ('sedimentation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='sedimentation rate (g /(cm2 x y)r)')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Sediment Contextual Data',
                'verbose_name_plural': 'Sediment Contextual Data',
            },
        ),
        migrations.AlterModelOptions(
            name='contextualopenwater',
            options={'verbose_name': 'Open Water Contextual Data', 'verbose_name_plural': 'Open Water Contextual Data'},
        ),
        migrations.AlterModelOptions(
            name='contextualpelagic',
            options={'verbose_name': 'Pelagic marine Contextual Data', 'verbose_name_plural': 'Pelagic marine Contextual Data'},
        ),
        migrations.AlterModelOptions(
            name='coral',
            options={'verbose_name': 'Coral Contextual Data', 'verbose_name_plural': 'Coral Contextual Data'},
        ),
        migrations.AlterModelOptions(
            name='seagrass',
            options={'verbose_name': 'Sea Grass Contextual Data', 'verbose_name_plural': 'Sea Grass Contextual Data'},
        ),
        migrations.AlterModelOptions(
            name='seaweed',
            options={'verbose_name': 'Seaweed Contextual Data', 'verbose_name_plural': 'Seaweed Contextual Data'},
        ),
    ]
