# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0009_auto_20160322_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponge',
            fields=[
                ('bpa_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='BPA ID')),
                ('date_sampled', models.DateField(verbose_name='Date Sampled')),
                ('time_sampled', models.TimeField(verbose_name='Time Sampled')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('dept', models.IntegerField(verbose_name='Depth')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('location_description', models.TextField(verbose_name='Location Description')),
                ('host_state', models.TextField(verbose_name='Host State')),
                ('host_abundance', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Host Abundance')),
            ],
            options={
                'verbose_name': 'Sponge Contextual Data',
                'verbose_name_plural': 'Sponge Contextual Data',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='seagrass',
            options={'verbose_name': 'Seagrass Contextual Data', 'verbose_name_plural': 'Seagrass Contextual Data'},
        ),
    ]
