# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_site_depth'),
        ('marine', '0010_auto_20160322_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextualopenwater',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Site'),
        ),
        migrations.AddField(
            model_name='contextualpelagic',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Site'),
        ),
        migrations.AddField(
            model_name='coral',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Site'),
        ),
        migrations.AddField(
            model_name='seagrass',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Site'),
        ),
        migrations.AddField(
            model_name='seaweed',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Site'),
        ),
        migrations.AddField(
            model_name='sediment',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Site'),
        ),
        migrations.AddField(
            model_name='sponge',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Site'),
        ),
    ]
