# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0011_auto_20160401_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextualopenwater',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='contextualopenwater',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='contextualopenwater',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='contextualpelagic',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='contextualpelagic',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='contextualpelagic',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='coral',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='coral',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='coral',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='seagrass',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='seagrass',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='seagrass',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='seaweed',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='seaweed',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='seaweed',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='sediment',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='sediment',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='sediment',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='sponge',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='sponge',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='sponge',
            name='lon',
        ),
    ]
