# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(help_text='Facility short name', max_length=100, primary_key=True, serialize=False, verbose_name='Facility Name'),
        ),
    ]
