# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20160112_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(choices=[('RAM', ' Ramaciotti'), ('AGRF', 'AGRF')], max_length=4, primary_key=True, serialize=False, verbose_name='Facility Name'),
        ),
    ]
